### ISSUE TITLE
Update tests to use `sdk` 

### ISSUE THREAD

**Issue by fibonacci1729** [spinframework/spin#216] opened 2022-03-23 01:07 UTC
The integration tests take a direct dependency on the relevant`wit` files; We should update these tests to use the `sdk`

**Comment by ejmg** [comment] 2022-06-03 22:09
Hey there, I might claim this issue. I started working with Spin and have at least one test going with the SDK instead of directly relying on the wit files & `wit_bindgen`. I'll PR my existing fork. What I'll need to know is how to enforce the actual intended behavior behind the integration tests given I'm not completely familiar with what is actually being enforced with respect to those wit files.

**Comment by radu-matei** [comment] 2022-06-07 00:39
That is great, thanks a lot, @ejmg!
Let us know if there is anything we can do to help.

**Comment by vdice** [comment] 2023-01-17 20:14
I revisited our tests today and as far as I can tell the only remaining test still using wit files is the [headers-env-routes-test](https://github.com/fermyon/spin/tree/main/tests/http/headers-env-routes-test).  It looks like there is an outstanding Draft PR in this area (#565), though it would need to be rebased or perhaps created anew.  Since we don't have an assignee at this time, I'm moving this into the Backlog.

**Closed as completed** 2023-01-18 20:19 UTC
Labels: good first issue, help wanted, sdk
